---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/kinigitbyday/dotfiles.git
dotfiles_push_url: git@github.com:kinigitbyday/dotfiles.git
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitignore
  - .osx
  - .zshrc
  - .custom_copper_zshrc

homebrew_installed_packages:
  - bitrise
  - chtf
  - coreutils
  - docker
  - fig
  - git
  - giter8
  - go
  - hub
  - imagemagick
  - neovim
  - node
  - nvm
  - openssl
  - python
  - python3
  - qrencode
  - ruby
  - sbt
  - sqlite
  - terraform
  - terraform_landscape
  - thefuck
  - wget
  - vegeta
  - vim
  - watchman
  - yarn
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - yleisradio/terraforms
  - homebrew/cask-versions
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - amethyst
  - android-ndk
  - android-platform-tools
  - android-sdk
  - boom-3d
  - chromedriver
  - db-browser-for-sqlite
  - discord
  - docker
  - figma
  - firefox
  - flipper
  - gimp
  - google-chrome
  - gpg-suite
  - insomnia
  - iterm2
  - karabiner-elements
  - licecap
  - macdown
  - mysqlworkbench
  - ngrok
  - pusher
  - signal
  - slack
  - sonos
  - sublime-text
  - temurin11
  - trailer
  - vagrant
  - visual-studio-code
  - webstorm
  - xquartz
  - ytmdesktop-youtube-music

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  - name: bundler
    version: "2.2.10"
  - name: cocoapods
    version: "1.11.2"
  - name: dotenv
    version: "2.7.6"
  - name: sqlite3
    version: "1.3.13"
  - name: cocoapods-user-defined-build-types
    version: "0.0.7"
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
