---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/kinigitbyday/dotfiles.git
dotfiles_push_url: git@github.com:kinigitbyday/dotfiles.git
dotfiles_repo_local_destination: ~/dev/dotfiles
dotfiles_files:
  - .gitignore
  - .osx
  - .zshrc

homebrew_installed_packages:
  - chtf
  - coreutils
  - git
  - giter8
  - go
  - neovim
  - node
  - nvm
  - openssl
  - python
  - python3
  - ruby
  - sbt
  - terraform
  - terraform_landscape
  - thefuck
  - wget
  - vegeta
  - vim
  - yarn
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - yleisradio/terraforms
  - caskformula/caskformula

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - google-play-music-desktop-player
  - java8
  - xquartz
  - inkscape
  - insomnia
  - iterm2
  - licecap
  - macdown
  - ngrok
  - sequel-pro
  - slack
  - sublime-text
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
