- name: Add unstage git alias
  git_config:
    name: alias.unstage
    scope: global
    value: reset HEAD --

- name: Add switch git alias
  git_config:
    name: alias.switch
    scope: global
    value: "!f() { git checkout $1 2>/dev/null || git checkout -b $1; }; f"

- name: Update default git editor to nvim
  git_config:
    name: core.editor
    scope: global
    value: /usr/local/bin/nvim

- name: Add osxkeychain as git credential helper
  git_config:
    name: credential.helper
    scope: global
    value: osxkeychain

- name: Add changes git alias
  git_config:
    name: alias.changes
    scope: global
    value: show --stat --oneline

- name: Add git commiter email
  git_config:
    name: user.email
    scope: global
    value: reid.knight@hey.com

- name: Add git commiter name
  git_config:
    name: user.name
    scope: global
    value: Reid
